openapi: 3.0.4
info:
  title: Marketplace log models
  description: Log models for logging services of marketplace
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        log:
          $ref: '#/components/schemas/MkplLogModel'

        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    MkplLogModel:
      title: Модель лога для сервиса Cat-Sitter
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/MkplLogOperation'
        request:
          $ref: '#/components/schemas/BookingLog'
        requestFilter:
          $ref: '#/components/schemas/FilterLogModel'
        response:
          $ref: '#/components/schemas/BookingLog'
        responses:
          type: array
          items:
            $ref: '#/components/schemas/BookingLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    MkplLogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - offers
        - init
        - finish

    BookingLog:
      title: Модель лога бронирования
      type: object
      properties:
        id:
          type: string
        ownerId:
          type: string
          format: uuid
        sitterId:
          type: string
          format: uuid
        notes:
          type: string

    FilterLogModel:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string
        dealSide:
          type: string